# Generated by Django 4.2.13 on 2024-05-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaservice',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
