# Generated by Django 4.2.13 on 2024-05-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_spaservice_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaservice',
            name='currency',
            field=models.CharField(default='SEK', max_length=3),
        ),
    ]
