# Generated by Django 4.2.13 on 2024-05-21 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_spaservice_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spaservice',
            name='date_and_time',
        ),
    ]
