# Generated by Django 4.2.13 on 2024-05-23 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_spaservice_available_date_spaservice_available_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spaservice',
            name='available',
        ),
        migrations.RemoveField(
            model_name='spaservice',
            name='available_date',
        ),
        migrations.RemoveField(
            model_name='spaservice',
            name='available_time',
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('spa_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.spaservice')),
            ],
        ),
    ]
