# Generated by Django 4.2.13 on 2024-06-26 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_specificdate_timeslot_remove_availability_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['time']},
        ),
    ]
