# Generated by Django 4.2.13 on 2024-06-26 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_timeslot_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specificdate',
            options={'ordering': ['date']},
        ),
    ]
