# Generated by Django 4.2.13 on 2024-07-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_specificdate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
