# Generated by Django 4.2.13 on 2024-07-27 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_spaservice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='spa_service',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='services.spaservice'),
        ),
    ]
