# Generated by Django 4.2.13 on 2024-07-27 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_spaservice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='spa_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.spaservice'),
        ),
    ]
