# Generated by Django 4.2.13 on 2024-07-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_alter_timeslot_spa_service'),
        ('services', '0015_remove_time_slots_field'),
    ]

    operations = [
    ]
