# Generated by Django 4.2.13 on 2024-07-29 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_remove_timeslot_is_available_timeslotavailability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='time_slots',
        ),
    ]
