# Generated by Django 4.2.13 on 2024-08-04 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0019_add_new_time_slots_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='new_time_slots',
            new_name='time_slots',
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('time', 'spa_service')},
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
                ('spa_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.spaservice')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
