# Generated by Django 4.2.13 on 2024-08-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_rename_new_time_slots_availability_time_slots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaservice',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
