# Generated by Django 4.2.13 on 2024-09-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_timeslotavailability_is_booked'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslotavailability',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='timeslotavailability',
            index=models.Index(fields=['specific_date', 'time_slot'], name='services_ti_specifi_01b94f_idx'),
        ),
    ]
