# Generated by Django 4.2.13 on 2024-09-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_alter_timeslotavailability_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificdate',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='time',
            field=models.TimeField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='timeslotavailability',
            unique_together={('availability', 'specific_date', 'time_slot')},
        ),
        migrations.AddIndex(
            model_name='specificdate',
            index=models.Index(fields=['date'], name='services_sp_date_d1fa5f_idx'),
        ),
    ]
