# Generated by Django 4.2.13 on 2024-06-06 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='customer',
            new_name='user',
        ),
    ]
