# Generated by Django 4.2.13 on 2024-06-20 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_customer_customerprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='default_email',
            new_name='email',
        ),
    ]
