# Generated by Django 4.2.13 on 2024-05-20 11:29

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(editable=False, max_length=35)),
                ('customer_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_and_time', models.DateTimeField()),
                ('booking_date', models.DateTimeField()),
                ('booking_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stripe_pid', models.CharField(default='', max_length=254)),
                ('customer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpaBookingServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('spa_service_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('spa_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spa_booking_services', to='booking.spabooking')),
                ('spa_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.spaservice')),
            ],
        ),
    ]
