# Generated by Django 4.2.13 on 2024-06-05 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_spabooking_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spabookingservices',
            name='date_and_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
