# Generated by Django 4.2.13 on 2024-06-07 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_customer_customerprofile_user'),
        ('booking', '0004_alter_spabooking_customer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spabooking',
            name='customer_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spa_bookings', to='accounts.customerprofile'),
        ),
    ]
