# Generated by Django 4.2.13 on 2024-06-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_spabooking_customer_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='spabooking',
            name='original_cart',
            field=models.TextField(default=''),
        ),
    ]
